<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "checkfaluploads"
 *
 * Auto generated by Extension Builder 2014-04-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'checkFalUploads',
	'description' => 'check fal uploads',
	'category' => 'be',
	'author' => 'Stefan Frömken',
	'author_email' => 'froemken@gmail.com',
	'author_company' => 'jweiland.net',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.2',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.2',
			'fluid' => '6.2',
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);