services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JWeiland\Checkfaluploads\:
    resource: '../Classes/*'

  JWeiland\Checkfaluploads\Service\FalUploadService:
    public: true
