services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JWeiland\Checkfaluploads\:
    resource: '../Classes/*'

  # Called by GeneralUtility::makeInstance in EXT:form -> FormRuntime::mapAndValidatePage
  JWeiland\Checkfaluploads\Hook\Form\DynamicUploadValidatorHook:
    public: true

  # Called by GeneralUtility::makeInstance in EXT:form -> AbstractFormFactory::triggerFormBuildingFinished
  JWeiland\Checkfaluploads\Hook\Form\ReplacePlaceholderHook:
    public: true

  JWeiland\Checkfaluploads\Controller\File\FileUploadController:
    tags:
      - name: 'backend.controller'
