# Adapted from https://github.com/TYPO3GmbH/blog/blob/master/.github/workflows/ci.yml
name: CI

on: [pull_request]

jobs:
  build:
    runs-on: 'ubuntu-18.04'
    name: PHP Unit and Functional Tests
    strategy:
      matrix:
        typo3: ['^9.5', '^10.4']
        php: ['7.2', '7.3', '7.4']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start MySQL Server
        if: ${{ env.GITHUB_ACTOR != 'nektos/act' }}
        run: sudo systemctl start mysql.service

      - name: Set up PHP Version ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, xml, ctype, iconv, intl, mysql
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies with typo3/cms-core:${{ matrix.typo3 }}
        run: |
          composer require typo3/cms-core:${{ matrix.typo3 }} --no-progress
          composer require typo3/cms-extensionmanager:${{ matrix.typo3 }} --no-progress
          git checkout composer.json

      - name: Functional Tests at Github
        if: ${{ env.GITHUB_ACTOR != 'nektos/act' }}
        env:
          typo3DatabaseDriver: pdo_sqlite
          COMPOSER_PROCESS_TIMEOUT: 600
        run: composer ci:tests:functional

      - name: Functional Tests locally
        if: ${{ env.GITHUB_ACTOR == 'nektos/act' }}
        env:
          typo3DatabaseDriver: pdo_sqlite
          COMPOSER_PROCESS_TIMEOUT: 600
        run: composer ci:tests:functional

  coding-standard:
    name: Coding Standard
    runs-on: 'ubuntu-18.04'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'
          extensions: mbstring, xml, ctype, iconv, intl
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies with typo3/cms-core:^10.4
        run: |
          composer require typo3/cms-core:^10.4 --no-progress
          composer require typo3/cms-extensionmanager:^10.4 --no-progress
          git checkout composer.json

      - name: php-cs-fixer
        run: composer ci:php:fixer

      - name: Lint PHP
        run: composer ci:php:lint
